version: '3.8'

services:
  app:
    build: .
    image: node:20
    container_name: sls-app-container
    ports:
      - "3070:3001"
    environment:
      - AWS_ACCESS_KEY=root
      - AWS_SECRET_ACCESS_KEY=root
      - AWS_REGION:eu-west-1
    working_dir: /project
    volumes:
      - ./src:/project
    depends_on:
      - db
    command: npm run dev

  db:
    container_name: sls-db-container
    image: amazon/dynamodb-local:latest
    ports:
      - "8070:8000"
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /usr/share/dynamodb
    volumes:
      - ./docker/dynamodb:/usr/share/dynamodb


