version: '3.8'

services:
  app:
    image: node:20
    container_name: app-container
    ports:
      - "3001:3001"
    working_dir: /usr/app/
    volumes:
      - ./src:/usr/app/
    command: npm run dev
    depends_on:
      - db
  db:
    image: mysql
    container_name: db-container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: false
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./data:/var/lib/mysql

